# Generated by Django 3.2.20 on 2024-09-10 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScormState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(help_text='example: course-v1:Org+Course+Run', max_length=255)),
                ('block_id', models.CharField(blank=True, max_length=255, null=True)),
                ('success_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('completion_status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('lesson_score', models.FloatField(blank=True, null=True)),
                ('session_times', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_key', 'block_id')},
            },
        ),
        migrations.CreateModel(
            name='ScormInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.CharField(max_length=255)),
                ('index', models.IntegerField()),
                ('type', models.CharField(choices=[('true-false', 'True False'), ('choice', 'Choice'), ('fill-in', 'Fill In'), ('matching', 'Matching'), ('performance', 'Performance'), ('sequencing', 'Sequencing'), ('likert', 'Likert'), ('numeric', 'Numeric')], default='', max_length=11)),
                ('student_response', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_responses', models.JSONField(default=list)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('weighting', models.FloatField(blank=True, null=True)),
                ('latency', models.DurationField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('scorm_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_interactions', to='openedxscorm.scormstate')),
            ],
            options={
                'unique_together': {('scorm_state', 'interaction_id', 'index')},
            },
        ),
    ]
