# Generated by Django 3.2.20 on 2024-09-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedxscorm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scormstate',
            old_name='complete_status',
            new_name='completion_status',
        ),
        migrations.RenameField(
            model_name='scormstate',
            old_name='lession_score',
            new_name='lesson_score',
        ),
        migrations.AlterUniqueTogether(
            name='scorminteraction',
            unique_together={('scorm_state', 'interaction_id', 'index')},
        ),
    ]
